### ISSUE TITLE
Uploading image on salesiq leads to crash

### ISSUE THREAD

**Issue by Mastersam07** [zoho/salesiq-mobilisten-flutter#38]
On android, uploading image on zoho leads to crash. Attached below is the stacktrace from the package when this happened:

```
D/skia    ( 1325): --- Failed to create image decoder with message 'unimplemented'
D/AndroidRuntime( 1325): Shutting down VM
E/AndroidRuntime( 1325): FATAL EXCEPTION: main
E/AndroidRuntime( 1325): Process: com.shuttlers.android, PID: 1325
E/AndroidRuntime( 1325): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/CircularProgressDrawable;
E/AndroidRuntime( 1325): 	at com.zoho.livechat.android.image.MobilistenImageUtil.loadImage$default(MobilistenImageUtil.kt:72)
E/AndroidRuntime( 1325): 	at com.zoho.livechat.android.image.MobilistenImageUtil.loadImage(Unknown Source:16)
E/AndroidRuntime( 1325): 	at com.zoho.livechat.android.ui.adapters.viewholder.MessagesImageViewHolder.render(MessagesImageViewHolder.java:165)
E/AndroidRuntime( 1325): 	at com.zoho.livechat.android.ui.adapters.MessagesAdapter.onBindViewHolder(MessagesAdapter.java:455)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
E/AndroidRuntime( 1325): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
E/AndroidRuntime( 1325): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
E/AndroidRuntime( 1325): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
E/AndroidRuntime( 1325): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
E/AndroidRuntime( 1325): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:804)
E/AndroidRuntime( 1325): 	at android.view.View.layout(View.java:23062)
E/AndroidRuntime( 1325): 	at android.view.ViewGroup.layout(ViewGroup.java:6468)
E/AndroidRuntime( 1325): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3588)
E/AndroidRuntime( 1325): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3056)
E/AndroidRuntime( 1325): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2057)
E/AndroidRuntime( 1325): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8362)
E/AndroidRuntime( 1325): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
E/AndroidRuntime( 1325): 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
E/AndroidRuntime( 1325): 	at android.view.Choreographer.doFrame(Choreographer.java:813)
E/AndroidRuntime( 1325): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
E/AndroidRuntime( 1325): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 1325): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1325): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 1325): 	at android.app.ActivityThread.main(ActivityThread.java:7861)
E/AndroidRuntime( 1325): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1325): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/AndroidRuntime( 1325): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime( 1325): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.CircularProgressDrawable" on path: DexPathList[[zip file "/data/app/~~u1Fxv7582bOf-hG_0LbEig==/com.shuttlers.android-1MpyRz1eBKwz9K4628WKyQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~u1Fxv7582bOf-hG_0LbEig==/com.shuttlers.android-1MpyRz1eBKwz9K4628WKyQ==/lib/arm64, /data/app/~~u1Fxv7582bOf-hG_0LbEig==/com.shuttlers.android-1MpyRz1eBKwz9K4628WKyQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 1325): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 1325): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 1325): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 1325): 	... 85 more
W/System  ( 1325): A resource failed to call close.
I/chatty  ( 1325): uid=10462(com.shuttlers.android) FinalizerDaemon identical 18 lines
W/System  ( 1325): A resource failed to call close.
I/Process ( 1325): Sending signal. PID: 1325 SIG: 9
Lost connection to device.

```

**Comment by DavidBhahirathan** [comment]
Hi @Mastersam07  ,

Thanks for writing to us. We'll look into this crash and update you here once resolved.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by Mastersam07** [comment]
Any update @DavidBhahirathan

**Comment by TouseefAQ** [comment]
@DavidBhahirathan Any update?

**Comment by DavidBhahirathan** [comment]
Hi.

Apologies for any inconvenience, @Mastersam07, and @TouseefAQ. The build is still in development and we will notify you once it has been released.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by DavidBhahirathan** [comment]
The screenshot feature is currently under development for Flutter. Unfortunately, it is not yet released, but you were able to access it due to a technical glitch. Rest assured that we are actively working to make this feature available to the public as soon as possible, and we will keep you informed of any updates.

**Comment by DavidBhahirathan** [comment]
Hi @Mastersam07, and @TouseefAQ ,

Thank you for your patience. We have fixed this issue. We recommend you update to the latest version [3.1.0](https://github.com/zoho/salesiq-mobilisten-flutter/releases/tag/v3.1.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.
