### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewModelKt

### ISSUE THREAD

**Issue by jghabacus** [zoho/salesiq-mobilisten-flutter#45]
From version 2.2.0 of the library we are having this issue in the Android version.
Everything is working well in iOS.

The issue is blocking since the application crash on Chat button opener (with show() method).

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewModelKt;
       at com.zoho.livechat.android.modules.conversations.ui.ConversationsViewModel.getLastMessages(ConversationsViewModel.kt:33)
       at com.zoho.livechat.android.ui.fragments.ConversationFragment.onCreateView(ConversationFragment.java:90)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
       at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:23454)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:23454)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
       at android.view.View.measure(View.java:23454)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
       at android.view.View.measure(View.java:23454)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:23454)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
       at android.view.View.measure(View.java:23454)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
       at android.view.View.measure(View.java:23454)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by DavidBhahirathan** [comment]
Hi @jghabacus ,

Thank you for writing to us. We'll look into this crash and update you here once it is fixed.

**Comment by DavidBhahirathan** [comment]
Hi @jghabacus,

Thank you for your patience. We have fixed this issue. We recommend you update to the latest version [3.1.0](https://github.com/zoho/salesiq-mobilisten-flutter/releases/latest), and verify. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.
